In [4]:
import numpy as np

W = np.random.random((5, 4))
print(W)
infl = np.array([0.1, 0.2, 0.4, 0.2, 0.1])
input = np.array([0, 1, 1, 0])
W += infl[:, np.newaxis] * (input - W)
print(W)

[[0.73768479 0.23227503 0.48982605 0.03258436]
 [0.50483371 0.30430349 0.05123884 0.57264763]
 [0.06328009 0.30736394 0.70267412 0.28469173]
 [0.93905372 0.02522636 0.14367384 0.19778432]
 [0.78011683 0.66315907 0.93924679 0.99352715]]
[[0.66391631 0.30904753 0.54084345 0.02932592]
 [0.40386697 0.44344279 0.24099107 0.45811811]
 [0.03796805 0.58441836 0.82160447 0.17081504]
 [0.75124297 0.22018109 0.31493907 0.15822746]
 [0.70210514 0.69684316 0.94532211 0.89417444]]
